name: gradle

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: temurin
      - uses: gradle/actions/setup-gradle@v3
      - run: ./gradlew build
