name: release

on:
  push:
    branches:
      - master

jobs:
  create:
    if: contains(github.event.head_commit.message, 'assignment-3')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: ./gradlew jar
      - run: gh release create v1.0.0 build/libs/software-design-vu-2024-1.0-SNAPSHOT.jar
        env:
          GH_TOKEN: ${{ github.token }}
